# name: Periodic health check

# on:
#   schedule:
#     - cron: '25,30 * * * *'

# jobs:
#   health_check:
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#       - name: health check
#         uses: jtalk/url-health-check-action@v2
#         with:
#           url: https://morning-gorge-87186.herokuapp.com/health
#           max-attempts: 3
#           retry-delay: 5s